In [1]:
import numpy as np

In [2]:
np.__version__

'1.15.4'

#### Python List的特点

In [3]:
L = [i for i in range(10)]

In [4]:
L

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [5]:
L[5]

5

In [6]:
L[5] = 100
L

[0, 1, 2, 3, 4, 100, 6, 7, 8, 9]

In [7]:
# 列表类型不限定

In [8]:
# 限定类型的列表
import array

In [9]:
arr = array.array('i', [i for i in range(10)])

In [10]:
arr

array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### numpy.array

In [11]:
nparr = np.array([i for i in range(10)])

In [12]:
nparr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### 限定类型

In [16]:
nparr.dtype

dtype('int32')

In [17]:
nparr2 = np.array([1, 2, 3.0])
nparr2.dtype

dtype('float64')

### 其他创建 numpy.array的方法

In [18]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [19]:
np.zeros(10).dtype

dtype('float64')

In [20]:
np.zeros(shape= (3, 5), dtype=int)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [21]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [27]:
np.full(fill_value=666.0, shape=(3,5))

array([[666., 666., 666., 666., 666.],
       [666., 666., 666., 666., 666.],
       [666., 666., 666., 666., 666.]])

### arange




In [32]:
[i for i in range(0, 20, 2)]

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]

In [33]:
np.arange(0, 20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [34]:
[i for i in range(0,20,0.2)]

TypeError: 'float' object cannot be interpreted as an integer

In [35]:
np.arange(0, 20, 0.5)

array([ 0. ,  0.5,  1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5,  5. ,
        5.5,  6. ,  6.5,  7. ,  7.5,  8. ,  8.5,  9. ,  9.5, 10. , 10.5,
       11. , 11.5, 12. , 12.5, 13. , 13.5, 14. , 14.5, 15. , 15.5, 16. ,
       16.5, 17. , 17.5, 18. , 18.5, 19. , 19.5])

### linspace

In [36]:
np.linspace(0, 20, 10)

array([ 0.        ,  2.22222222,  4.44444444,  6.66666667,  8.88888889,
       11.11111111, 13.33333333, 15.55555556, 17.77777778, 20.        ])

In [37]:
np.linspace(0, 20, 11)

array([ 0.,  2.,  4.,  6.,  8., 10., 12., 14., 16., 18., 20.])

### random

In [38]:
np.random.randint(0, 10)

2

In [39]:
np.random.randint(0, 10 ,10)

array([9, 2, 2, 9, 3, 6, 2, 2, 0, 8])

In [40]:
np.random.randint(4, 8 , size=10)

array([4, 4, 6, 4, 4, 4, 5, 5, 6, 6])

In [42]:
np.random.randint(4, 8, size=(3,5))

array([[4, 6, 5, 7, 5],
       [5, 7, 4, 7, 5],
       [4, 4, 6, 6, 5]])

In [43]:
np.random.seed(666)

In [44]:
np.random.randint(4, 8, size=(3,5))

array([[4, 6, 5, 6, 6],
       [6, 5, 6, 4, 5],
       [7, 6, 7, 4, 7]])

In [45]:
np.random.seed(666)
np.random.randint(4,8,size=(3,5))

array([[4, 6, 5, 6, 6],
       [6, 5, 6, 4, 5],
       [7, 6, 7, 4, 7]])