In [2]:
import numpy as np
import matplotlib.pyplot as plt
from sklearn import datasets

In [4]:
iris = datasets.load_iris()
iris.keys()

dict_keys(['data', 'target', 'target_names', 'DESCR', 'feature_names', 'filename'])

In [5]:
X = iris.data

In [6]:
y = iris.target

In [8]:
X.shape

(150, 4)

In [10]:
y.shape

(150,)

### 训练数据 测试数据分离

In [11]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [12]:
shuffled_indexes = np.random.permutation(len(X))
shuffled_indexes

array([ 26,  65, 147,  34,  57, 104, 140,   4, 118,  66,  83,  15, 123,
        28, 143,  62, 109,  33,  17,  64,   7,  27, 135, 112,  46, 141,
        11, 137, 121,  22,  43, 124,  38,  73,  99,  36,  60,  52,  41,
        20,  95,  35,  32,  45, 139, 136,  75, 117,  72,  85,  59, 111,
        87, 131,  56,  18,   9,  82,  69, 105,  67,  24, 138,  63, 110,
        25, 128, 129, 126,   5,  68, 122,  90, 130, 102, 100, 134,   3,
        74,  42, 146,   1,  58,  76,  70,  55, 103,   2,  92,  97,  13,
        16,  12,  91, 114,  53,  86,  44,  93,  79,  23,  88, 149, 119,
        48, 101,  61,  21, 133,  96, 120,  89,  81, 115,  50, 144,  19,
       106, 145,  77,  84, 127,  30,  29,  54, 113,  78, 107,  10,  37,
        51, 125, 142,   8,  14,  94,   0,  71,  40, 108,  49,  47,  98,
        80,   6,  39, 132, 148, 116,  31])

In [13]:
test_ratio = 0.2 # 测试数据占比
test_size = int(len(X) * test_ratio)

In [14]:
test_indexes = shuffled_indexes[:test_size]
train_indexes = shuffled_indexes[test_size:]

In [15]:
X_train = X[train_indexes]
y_train = y[train_indexes]

X_test = X[test_indexes]
y_test = y[test_indexes]

In [16]:
print(X_train.shape)
print(y_train.shape)

(120, 4)
(120,)


In [17]:
print(X_test.shape)
print(y_test.shape)

(30, 4)
(30,)


#### 封装

In [18]:
from playML.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y)

In [19]:
print(X_train.shape)
print(y_train.shape)

(120, 4)
(120,)


In [20]:
print(X_test.shape)
print(y_test.shape)

(30, 4)
(30,)


In [21]:
## 测试算法
from playML.kNN import KNNClassifier

my_knn_clf = KNNClassifier(k=3)
my_knn_clf.fit(X_train, y_train)
y_predict = my_knn_clf.predict(X_test)

In [22]:
y_predict

array([1, 0, 0, 0, 0, 1, 1, 0, 2, 0, 0, 2, 0, 0, 0, 2, 0, 2, 0, 2, 1, 2,
       1, 2, 1, 1, 1, 1, 1, 2])

In [23]:
y_test

array([1, 0, 0, 0, 0, 1, 1, 0, 2, 0, 0, 2, 0, 0, 0, 2, 0, 2, 0, 2, 1, 2,
       1, 2, 1, 1, 1, 1, 1, 2])

In [24]:
sum(y_predict==y_test)

30

#### scikit-learn中的train_test_split函数

In [25]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=666)

In [26]:
print(X_train.shape)
print(y_train.shape)

print(X_test.shape)
print(y_test.shape)

(120, 4)
(120,)
(30, 4)
(30,)
